//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Lamp.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define ID_VIEW_CUSTOMIZE               124
#define IDR_MAINFRAME                   125
#define IDR_MAINFRAME_256               126
#define IDR_LampTYPE                    127
#define ID_WINDOW_MANAGER               128
#define IDS_WINDOWS_MANAGER             129
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDR_POPUP_COPYLINK_MENU         202
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EDIT_MENU                   306
#define IDD_OPENTHREAD_DIALOG           307
#define IDD_FINDTEXT_DIALOG             308
#define IDD_LOGIN_DIALOG                309
#define IDD_AUTHOR_DIALOG               322
#define IDD_DOCKTAB                     323
#define IDD_SEARCH_DIALOG               324
#define IDD_BOOKMARK_DIALOG             325
#define IDD_SENDMSG_DIALOG              326
#define IDD_SETTINGS_DIALOG             327
#define IDC_THREAD_EDIT                 1000
#define IDC_FIND_EDIT                   1001
#define IDC_USERNAME_EDIT               1002
#define IDC_PASSWORD_EDIT               1003
#define IDC_INFO_EDIT                   1004
#define IDC_SHACKPAGE_BUTTON            1005
#define IDC_SEARCH_TERMS_EDIT           1006
#define IDC_SEARCH_USER_EDIT            1007
#define IDC_SEARCH_PARENT_EDIT          1008
#define IDC_TO_EDIT                     1008
#define IDC_BM_TITLE_EDIT               1009
#define IDC_SUBJECT_EDIT                1010
#define IDC_SHACKMSG_EDIT               1011
#define IDC_MOUSE_WHEEL_SPEED_EDIT      1012
#define IDC_MB_PAN_SPEED_EDIT           1013
#define IDC_NUM_SHOW_TRUNC_EDIT         1014
#define IDC_NUM_MIN_INBOX_EDIT          1015
#define IDC_NUM_HOURS_EXPIRE_EDIT       1016
#define ID_FILE_OPENTHREAD              32771
#define ID_EDIT_REFRESH                 32773
#define ID_FILE_SETUPLOGININFO          32774
#define ID_VIEW_SMOOTHSCROLL            32775
#define ID_EDIT_NEWTHREAD               32776
#define ID_COPYLINK                     32777
#define IDS_COPYLINK_MENU               32778
#define ID_VIEW_INCREASEFONTSIZE        32779
#define ID_VIEW_DECREASEFONTSIZE        32780
#define ID_VIEW_RESETFONTSIZE           32781
#define ID_VIEW_DOCKTOP                 32786
#define ID_LOL_LOL                      32787
#define ID_LOL_INF                      32788
#define ID_LOL_UNF                      32789
#define ID_LOL_TAG                      32790
#define ID_LOL_WTF                      32791
#define ID_LOL_THINGS_I_LOLD            32792
#define ID_LOL_THINGS_I_WROTE           32793
#define ID_LOL_GOTO_LOL                 32794
#define ID_LAUNCHLINK                   32795
#define ID_MY_COMMENTS                  32796
#define ID_VANITY_SEARCH                32797
#define ID_SHACK_SEARCH                 32798
#define ID_REPLIES_TO_ME                32799
#define ID_VIEW_AUTOSHOWLOADEDIMAGES    32800
#define ID_EDIT_LOADALLIMAGES           32801
#define ID_EDIT_CLOSEALLIMAGES          32802
#define ID_BOOKMARK_MENU                32803
#define IDR_POPUP_BOOKMARK_MENU         32804
#define ID_BOOKMARK_ADD                 32805
#define ID_EDIT_BOOKMARK_THIS_POST      32806
#define ID_PINNING_MENUITEM             32807
#define ID_CLEAR_ALL_PINNINGS_MENUITEM  32808
#define ID_DOUBLE_PAGE_STORY_MENUITEM   32809
#define ID_OPENINTAB                    32810
#define ID_ALWAYSONTOP_WHENNOTDOCKED    32811
#define ID_EDIT_PASTE_LAST_POST         32812
#define ID_HELP_WIKI                    32813
#define ID_SHKMSGS_INBOX                32814
#define ID_SHKMSGS_OUTBOX               32815
#define ID_SHKMSGS_ARCHIVE              32816
#define ID_AUTHORDLG_SEARCH_BUTTON      32817
#define ID_AUTHORDLG_MESSAGE_BUTTON     32818
#define ID_FIND_NEXT_BUTTON             32819
#define ID_SHOW_LOL_BUTTONS             32820
#define ID_CHECK_SPELLING               32821
#define ID_FILTER_ENABLE_NWS            32822
#define ID_FILTER_ENABLE_INF            32823
#define ID_FILTER_ENABLE_OFFTOPIC       32824
#define ID_FILTER_ENABLE_STUPID         32825
#define ID_FILTER_ENABLE_POLITICAL      32826
#define ID_SKIN_ROUNDSHACK              32827
#define ID_SKIN_DEFAULT                 32828
#define ID_SKIN_CUSTOM                  32829
#define ID_HIGHLIGHT_OP                 32830
#define ID_SHOW_SETTINGS_DIALOG         32831
#define ID_NORM_FONT                    32832
#define ID_QUOTE_FONT                   32833
#define ID_CODE_FONT                    32834
#define ID_SMALL_LOL                    32835
#define ID_SELECT_DARK_BLUE             32836
#define ID_SELECT_BLUE                  32837
#define ID_SELECT_YELLOW                32838
#define ID_SELECT_PALE_YELLOW           32839
#define ID_SELECT_CUSTOM                32840
#define ID_FLAREDBRANCHES               32841
#define ID_GOOGLE_SELECTED              32842
#define ID_GOOGLE_SELECTED_W_QUOTES     32843
#define ID_WIKIPEDIA_SELECTED           32844
#define IDC_INERTIA_EDIT                32845
#define ID_AUTOCHECKINBOX               32846

#define ID_BOOKMARK_MENUITEM            32852

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
